routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('siswa/login', function(){
    return view('auth/login-siswa');
});
Route::post('siswa/login', 'Auth\LoginSiswaController@login')->name('siswa.login');
Route::post('siswa/logout', 'Auth\LoginSiswaController@logout')->name('siswa.logout');
Route::middleware(['auth:siswa'])->prefix('siswa')->group(function(){
    Route::get('dashboard', 'DashboardController@indexSiswa')->name('siswa.dashboard');
    Route::get('kelas', 'KelasController@index')->name('siswa.kelas.index');
    Route::get('kelas/{id}/siswa', 'KelasController@kelasSiswa')->name('siswa.kelas.detail');
    Route::get('pengumuman', 'PengumumanController@index')->name('siswa.pengumuman');
    Route::get('pengumuman/{id}', 'PengumumanController@show')->name('siswa.pengumuman.show');

    Route::get('materi-tugas', 'MateriTugasController@index')->name('siswa.materi-tugas.index');
    Route::get('materi-tugas/{id}', 'MateriTugasController@show')->name('siswa.materi-tugas.show');
    Route::post('materi-tugas/{id}', 'MateriTugasController@submitJawaban')->name('siswa.jawaban');
});

Route::get('/', function () {
    return view('auth/login-siswa');
});

Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', function(){
        return view('dashboard');
    });
    Route::resource('kelas', 'KelasController');
    Route::resource('siswa', 'SiswaController')->middleware('auth:web');
    Route::resource('user', 'UserController')->middleware('auth:web');
    Route::get('kelas/{id}/siswa', 'KelasController@kelasSiswa')->name('kelas.siswa');
    Route::post('kelas/{id}/siswa', 'KelasController@simpanSiswa')->name('kelas.siswa.store');
    Route::delete('kelas/{id}/siswa', 'KelasController@deleteKelasSiswa')->name('kelas.siswa.destroy');

    Route::resource('pengumuman', 'PengumumanController')->middleware('auth:web');
    Route::resource('materi-tugas', 'MateriTugasController');
});

app/Http/Controllers/MateriTugasController.php
<?php

namespace App\Http\Controllers;

use App\Jawaban;
use App\Kelas;
use App\Materi;
use App\Siswa;
use App\Tugas;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class MateriTugasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(Auth::guard('web')->check()){
            $data['kelas'] = Kelas::where('status', 1)->orderBy('nama_kelas', 'asc')->get();
            if(isset($request['kelas_id'])) {
                $data['materi'] = Materi::where('kelas_id', $request->kelas_id)->get();
                $data['tugas'] = Tugas::where('kelas_id', $request->kelas_id)->get();
                $data['detail_kelas'] = Kelas::findOrFail($request->kelas_id);
            }
        } else {
            $data['kelas'] = Siswa::find(Auth::user()->id)->getKelasSiswa();
            $data['materi'] = Materi::where('kelas_id', $data['kelas'][0]->id)->where('status', 1)->get();
            $data['tugas'] = Tugas::where('kelas_id', $data['kelas'][0]->id)->where('status', 1)->get();
            $data['detail_kelas'] = Kelas::findOrFail($data['kelas'][0]->id);
        }
        return view('materi_tugas.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $data['type'] = $request->type;
        $data['kelas'] = Kelas::findOrFail($request->kelas_id);

        if($data['type'] == 'materi') {
            $data['materi_tugas'] = Materi::getDefaultValues();
        }
        if($data['type'] == 'tugas') {
            $data['materi_tugas'] = Tugas::getDefaultValues();
        }
        return view('materi_tugas.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'tgl' => 'required',
            'deskripsi' => 'required',
            'status' => 'required',
        ]);
        $input = $request->toArray();
        $type = $input['type'];
        $input['user_id'] = Auth::user()->id;
        if($request->hasFile('file')){
            $request->file('file')->store('file_'.$input['type']);
            $input['file_'.$input['type']] = $request->file('file')->hashName();
        }

        if($input['type'] == 'materi'){
            unset($input['type']);
            Materi::create($input);
            return redirect('materi-tugas?kelas_id='.$input['kelas_id'])->with('success', 'Berhasil menambah '. $type .' pada kelas');
        }
        if($input['type'] == 'tugas'){
            unset($input['type']);
            Tugas::create($input);
            return redirect('materi-tugas?kelas_id='.$input['kelas_id'])->with('success', 'Berhasil menambah '. $type .' pada kelas');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['type'] = request()->type;
        $data['kelas'] = Kelas::findOrFail(request()->kelas_id);

        if($data['type'] == 'materi') {
            $data['materi_tugas'] = Materi::findOrFail($id);
        }
        if($data['type'] == 'tugas') {
            $data['materi_tugas'] = Tugas::findOrFail($id);
            if(Auth::guard('web')->check()){
                $data['jawaban'] = Jawaban::where('tugas_id', $id)->get();
            } else {
                $data['jawaban'] = Jawaban::where('tugas_id', $id)->where('siswa_id', Auth::guard('siswa')->user()->id)->get();
            }
        }
        return view('materi_tugas.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $data['type'] = request()->type;
        $data['kelas'] = Kelas::findOrFail(request()->kelas_id);

        if($data['type'] == 'materi') {
            $data['materi_tugas'] = Materi::findOrFail($id);
        }
        if($data['type'] == 'tugas') {
            $data['materi_tugas'] = Tugas::findOrFail($id);
        }
        return view('materi_tugas.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required',
            'tgl' => 'required',
            'deskripsi' => 'required',
            'status' => 'required',
        ]);
        $input = $request->toArray();
        if($input['type'] == 'materi') {
            $materi_tugas = Materi::findOrFail($id);
        } else {
            $materi_tugas = Tugas::findOrFail($id);
        }
        $input['user_id'] = Auth::user()->id;
        if($request->hasFile('file')){
            Storage::delete('file_'. $input['type'] . '/' .$materi_tugas->file_.$input['type']);
            $request->file('file')->store('file_'.$input['type']);
            $input['file_'.$input['type']] = $request->file('file')->hashName();
        }
        $type = $input['type'];
        unset($input['type']);
        $materi_tugas->update($input);


        return redirect('materi-tugas?kelas_id='.$input['kelas_id'])->with('success', 'Berhasil mengubah '.$type.' pada kelas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(request()->type == 'materi') {
            $materi_tugas = Materi::findOrFail($id);
            Storage::delete('file_materi/'.$materi_tugas->file_materi);
        }
        if(request()->type == 'tugas') {
            $materi_tugas = Tugas::findOrFail($id);
            Storage::delete('file_tugas/'.$materi_tugas->file_tugas);
        }
        $materi_tugas->delete();
        return redirect()->back()->with('success', 'Berhasil menghapus '.request()->type.' pada kelas');
    }

    public function submitJawaban(Request $request, $id)
    {
        $request->validate([
            'file_jawaban' => 'required'
        ]);

        $request->file('file_jawaban')->store('file_jawaban');
        $input['file_jawaban'] = $request->file('file_jawaban')->hashName();
        $input['tugas_id'] = $id;
        $input['siswa_id'] = Auth::user()->id;
        $input['tgl'] = date('Y-m-d');
        Jawaban::create($input);
        return redirect()->back()->with('success', 'Submit jawaban berhasil');

    }
}

resources/views/materi_tugas/form.blade.php
@extends('layouts.app')

@section('title')
Form {{ $type }}
@endsection

@section('content')
    <div class="header bg-primary pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">{{ ucwords($type) }} Kelas {{ $kelas->nama_kelas }}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid mt--5">
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                  <div class="row align-items-center">
                    <div class="col-12">
                      <h3 class="mb-0">Form {{ ucwords($type) }}</h3>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <form action="{{ (!isset($materi_tugas['id'])) ? route('materi-tugas.store') : route('materi-tugas.update', $materi_tugas['id']) }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @isset($materi_tugas['id'])
                            {{ method_field('PUT')}}
                        @endisset
                        <div class="pl-lg-4">
                            <input type="hidden" name="kelas_id" value="{{ $kelas->id }}">
                            <input type="hidden" name="type" value="{{ $type }}">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Nama {{ $type }}</label>
                                        <input type="text" class="form-control" name="nama" placeholder="" value="{{ old('nama', $materi_tugas['nama']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Tanggal</label>
                                        <input type="text" class="form-control datepicker" name="tgl" placeholder="" value="{{ old('tgl', $materi_tugas['tgl']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>File</label>
                                        <input type="file" class="form-control" name="file" placeholder="" value="{{ old('file', $materi_tugas['file_'.$type]) }}">
                                        @isset($materi_tugas['id'])
                                            <p class="mt-3">{!! $materi_tugas->getFile() !!}</p>
                                        @endisset
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Deskripsi</label>
                                        <textarea type="text" class="form-control" name="deskripsi" placeholder="" rows="7">{{ old('deskripsi', $materi_tugas['deskripsi']) }}</textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <select name="status" class="form-control">
                                            <option value="1" {{ old('status', $materi_tugas['status']) == "1" ? 'selected' : '' }}>Aktif</option>
                                            <option value="0" {{ old('status', $materi_tugas['status']) == "0" ? 'selected' : '' }}>Tidak Aktif</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group text-right">
                                        <input type="submit" value="Simpan" class="btn btn-success">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/materi_tugas/index.blade.php
@extends('layouts.app')

@section('title', 'Materi & Tugas')

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Materi & Tugas</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid mt--5">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col-12">
                            <h3 class="mb-0">Kelas</h3>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @if(Auth::guard('web')->check())
                        <form action="" method="get">
                            <div class="form-group">
                                <label>Nama Kelas</label>
                                <select name="kelas_id" class="form-control select2">
                                    <option value="">- Pilih Kelas -</option>
                                    @foreach($kelas as $option)
                                        <option value="{{ $option->id }}" {{ request('kelas_id') == $option->id ? 'selected' : '' }}>{{ $option->nama_kelas }} - {{ $option->tahun_ajar }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group mb-0 text-right">
                                <input type="submit" class="btn btn-success" value="Cari">
                            </div>
                        </form>
                    @else
                        <div class="form-group">
                            <label>Nama Kelas</label>
                            <input type="text" name="" value="{{ $kelas[0]->nama_kelas }}" readonly class="form-control">
                        </div>
                    @endif
                </div>
            </div>
        </div>
        @if(!empty(request('kelas_id')) || isset($detail_kelas))
            <div class="col-12">
                <div class="nav-wrapper">
                    <ul class="nav nav-pills nav-fill flex-column flex-md-row" id="tabs-icons-text" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link mb-sm-3 mb-md-0 active" id="materi-tab" data-toggle="tab" href="#materi-tab-text" role="tab" aria-controls="materi-tab-text" aria-selected="true"><i class="fa fa-book mr-2"></i>Materi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link mb-sm-3 mb-md-0" id="tugas-tab" data-toggle="tab" href="#tugas-tab-text" role="tab" aria-controls="tugas-tab-text" aria-selected="false"><i class="fa fa-clipboard-list mr-2"></i>Tugas</a>
                        </li>
                    </ul>
                </div>

                <div class="tab-content" id="">
                    <div class="tab-pane fade show active" id="materi-tab-text" role="tabpanel" aria-labelledby="materi-tab">
                        <div class="card">
                            <div class="card-header border-0">
                                <div class="row align-items-center">
                                    <div class="col">
                                        <h3 class="mb-0">Data Materi Kelas {{ $detail_kelas->nama_kelas }}</h3>
                                    </div>
                                    <div class="col text-right">
                                        @if(Auth::guard('web')->check())
                                            <a href="{{ route('materi-tugas.create') . '?type=materi&kelas_id='.$detail_kelas->id }}" class="btn btn-sm btn-primary">Tambah</a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table align-items-center table-flush">
                                    <thead class="thead-light">
                                        <tr>
                                            <th>No</th>
                                            <th>Materi</th>
                                            <th>Tanggal</th>
                                            <th>File</th>
                                            <th>Status</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse($materi as $row)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $row->nama }}</td>
                                                <td>{{ $row->tgl }}</td>
                                                <td>{!! $row->getFile() !!}</td>
                                                <td>{!! $row->getStatus() !!}</td>
                                                <td>
                                                    @if(Auth::guard('web')->check())
                                                    <form action="{{ route('materi-tugas.destroy', $row->id) . '?type=materi&kelas_id='.$detail_kelas->id }}" method="post">
                                                        @csrf
                                                        @method('delete')
                                                        <a href="{{ route('materi-tugas.show', $row->id) . '?type=materi&kelas_id='.$detail_kelas->id }}" class="btn btn-sm btn-info" title="Lihat detail"><i class="fa fa-eye"></i></a>
                                                        <a href="{{ route('materi-tugas.edit', $row->id) . '?type=materi&kelas_id='.$detail_kelas->id }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                                        <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                                    </form>
                                                    @else
                                                        <a href="{{ route('siswa.materi-tugas.show', $row->id) . '?type=materi&kelas_id='.$detail_kelas->id }}" class="btn btn-sm btn-info" title="Lihat detail"><i class="fa fa-eye"></i></a>
                                                    @endif
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="7">Belum ada data</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="tab-pane fade" id="tugas-tab-text" role="tabpanel" aria-labelledby="tugas-tab">
                        <div class="card">
                            <div class="card-header border-0">
                                <div class="row align-items-center">
                                    <div class="col">
                                        <h3 class="mb-0">Data Tugas Kelas {{ $detail_kelas->nama_kelas }}</h3>
                                    </div>
                                    <div class="col text-right">
                                        @if(Auth::guard('web')->check())
                                            <a href="{{ route('materi-tugas.create') . '?type=tugas&kelas_id='.$detail_kelas->id }}" class="btn btn-sm btn-primary">Tambah</a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table align-items-center table-flush">
                                    <thead class="thead-light">
                                        <tr>
                                            <th>No</th>
                                            <th>Tugas</th>
                                            <th>Tanggal</th>
                                            <th>File</th>
                                            <th>Status</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @forelse($tugas as $row)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $row->nama }}</td>
                                                <td>{{ $row->tgl }}</td>
                                                <td>{!! $row->getFile() !!}</td>
                                                <td>{!! $row->getStatus() !!}</td>
                                                <td>
                                                    @if(Auth::guard('web')->check())
                                                        <form action="{{ route('materi-tugas.destroy', $row->id) . '?type=tugas&kelas_id='.$detail_kelas->id }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            <a href="{{ route('materi-tugas.show', $row->id) . '?type=tugas&kelas_id='.$detail_kelas->id }}" class="btn btn-sm btn-info" title="Lihat detail"><i class="fa fa-eye"></i></a>
                                                            <a href="{{ route('materi-tugas.edit', $row->id) . '?type=tugas&kelas_id='.$detail_kelas->id }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                                            <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                                        </form>
                                                    @else
                                                        <a href="{{ route('siswa.materi-tugas.show', $row->id) . '?type=tugas&kelas_id='.$detail_kelas->id }}" class="btn btn-sm btn-info" title="Lihat detail"><i class="fa fa-eye"></i></a>
                                                    @endif
                                                </td>
                                            </tr>
                                        @empty
                                            <tr>
                                                <td colspan="7">Belum ada data</td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        @endif
    </div>
@endsection

resources/views/materi_tugas/show.blade.php
@extends('layouts.app')

@section('title')
Detail {{ $type }}
@endsection

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Detail {{ $type }}</h6>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">{{ $materi_tugas->nama }}</h3>
                            </div>
                            <div class="col text-right">
                                {!! $materi_tugas->getStatus() !!}
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>{{ $materi_tugas->tgl }}</p>
                        @if($materi_tugas->getFile() != 'Tidak ada file')
                            <p>{!! $materi_tugas->getFile() !!}</p>
                        @endif
                        <pre style="font-family: 'Open Sans'; line-height:1.8em; color:#525f7f;">{{ $materi_tugas->deskripsi }}</pre>
                    </div>
                </div>
            </div>
        </div>
        @if(request()->type == 'tugas')
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Jawaban Siswa</h3>
                            </div>
                            <div class="col text-right">
                                @if(Auth::guard('siswa')->check() && $jawaban->count() == 0)
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#formJawaban">
                                    Tambah Jawaban
                                </button>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Nama Siswa</th>
                                    <th>No Siswa</th>
                                    <th>Tanggal</th>
                                    <th>File Jawaban</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($jawaban as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $row->siswa->nama }}</td>
                                        <td>{{ $row->siswa->no_siswa }}</td>
                                        <td>{{ $row->tgl }}</td>
                                        <td><a href="{{ asset('storage/file_jawaban/'.$row->file_jawaban) }}" download>Download Jawaban</a></td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5">Belum ada jawaban</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @endif
    </div>

    @if(Auth::guard('siswa')->check())
    <!-- Modal -->
    <div class="modal fade" id="formJawaban" tabindex="-1" role="dialog" aria-labelledby="formJawabanLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="formJawabanLabel">Tambah Siswa</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('siswa.jawaban', $materi_tugas->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="">File Jawaban</label>
                            <input type="file" name="file_jawaban" id="" class="form-control" required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @endif
@endsection