routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('siswa/login', function(){
    return view('auth/login-siswa');
});
Route::post('siswa/login', 'Auth\LoginSiswaController@login')->name('siswa.login');
Route::post('siswa/logout', 'Auth\LoginSiswaController@logout')->name('siswa.logout');
Route::middleware(['auth:siswa'])->prefix('siswa')->group(function(){
    Route::get('dashboard', 'DashboardController@indexSiswa')->name('siswa.dashboard');
    Route::get('kelas', 'KelasController@index')->name('siswa.kelas.index');
    Route::get('kelas/{id}/siswa', 'KelasController@kelasSiswa')->name('siswa.kelas.detail');
    Route::get('pengumuman', 'PengumumanController@index')->name('siswa.pengumuman');
    Route::get('pengumuman/{id}', 'PengumumanController@show')->name('siswa.pengumuman.show');

    Route::get('materi-tugas', 'MateriTugasController@index')->name('siswa.materi-tugas.index');
    Route::get('materi-tugas/{id}', 'MateriTugasController@show')->name('siswa.materi-tugas.show');
    Route::post('materi-tugas/{id}', 'MateriTugasController@submitJawaban')->name('siswa.jawaban');
});

Route::get('/', function () {
    return view('auth/login-siswa');
});

Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', function(){
        return view('dashboard');
    });
    Route::resource('kelas', 'KelasController');
    Route::resource('siswa', 'SiswaController')->middleware('auth:web');
    Route::resource('user', 'UserController')->middleware('auth:web');
    Route::get('kelas/{id}/siswa', 'KelasController@kelasSiswa')->name('kelas.siswa');
    Route::post('kelas/{id}/siswa', 'KelasController@simpanSiswa')->name('kelas.siswa.store');
    Route::delete('kelas/{id}/siswa', 'KelasController@deleteKelasSiswa')->name('kelas.siswa.destroy');

    Route::resource('pengumuman', 'PengumumanController')->middleware('auth:web');
    Route::resource('materi-tugas', 'MateriTugasController');
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nama',
        'email',
        'username',
        'password',
        'alamat',
        'no_telp',
        'tempat_lhr',
        'tgl_lhr',
        'j_kel',
        'level',
        'status',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getDefaultValues()
    {
        return [
            'nama' => '',
            'email' => '',
            'username' => '',
            'password' => '',
            'alamat' => '',
            'no_telp' => '',
            'tempat_lhr' => '',
            'tgl_lhr' => '',
            'j_kel' => '',
            'level' => '',
            'status' => '',
        ];
    }

    public function getStatus() {
        if ($this->status == "1") {
            return '<span class="badge badge-success">Aktif</span>';
        } else {
            return '<span class="badge badge-warning">Tidak Aktif</span>';
        }
    }

    public function getLevel() {
        if ($this->level == "1") {
            return '<span class="badge badge-secondary">Guru</span>';
        } else {
            return '<span class="badge badge-info">Admin</span>';
        }
    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUser;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $user;

    public function __construct()
    {
        $this->user = new User();
    }

    public function index()
    {
        return view ('user.index', ['users' => $this->user->all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['user'] = $this->user->getDefaultValues();

        return view('user.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
    	$request['password'] = bcrypt($request['password']);
        User::create($request->toArray());
        return redirect()->route('user.index')->with('success', 'Berhasil menambah data petugas');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['user'] = $this->user->find($id);

        return view('user.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUser $request, $id)
    {
        $input = $request->toArray();
        if(empty($input['password'])) {
            unset($input['password']);
        } else {
            $input['password'] = bcrypt($input['password']);
        }
        $this->user->find($id)->update($input);
        return redirect()->route('user.index')->with('success', 'Berhasil mengubah data petugas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->user->find($id)->delete();
        return redirect()->route('user.index')->with('success', 'Berhasil menghapus data petugas');
    }
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('title', 'Form user')

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">User</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                  <div class="row align-items-center">
                    <div class="col-12">
                      <h3 class="mb-0">Form User</h3>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <form action="{{ (!isset($user['id'])) ? route('user.store') : route('user.update', $user['id']) }}" method="post">
                        @csrf
                        @isset($user['id'])
                            {{ method_field('PUT')}}
                        @endisset
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input type="text" class="form-control" name="username" placeholder="" value="{{ old('username', $user['username']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input type="password" class="form-control" name="password" placeholder="" value="{{ old('password') }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Nama Lengkap</label>
                                        <input type="text" class="form-control" name="nama" placeholder="" value="{{ old('nama', $user['nama']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="email" class="form-control" name="email" placeholder="" value="{{ old('email', $user['email']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Tempat Lahir</label>
                                        <input type="text" class="form-control" name="tempat_lhr" placeholder="" value="{{ old('tempat_lhr', $user['tempat_lhr']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Tanggal Lahir</label>
                                        <input type="text" class="form-control datepicker" name="tgl_lhr" placeholder="" value="{{ old('tgl_lhr', $user['tgl_lhr']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>Jenis Kelamin</label><br>
                                        <div class="custom-control custom-radio custom-control-inline">
                                            <input type="radio" id="j_kel" name="j_kel" class="custom-control-input" value="l" {{ old('j_kel', $user['j_kel']) == "l" ? 'checked' : '' }}>
                                            <label class="custom-control-label" for="j_kel">Laki - Laki</label>
                                          </div>
                                          <div class="custom-control custom-radio custom-control-inline">
                                            <input type="radio" id="customRadioInline2" name="j_kel" class="custom-control-input" value="p" {{ old('j_kel', $user['j_kel']) == "p" ? 'checked' : '' }}>
                                            <label class="custom-control-label" for="customRadioInline2">Perempuan</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>No. Telp</label>
                                        <input type="number" class="form-control" name="no_telp" placeholder="" value="{{ old('no_telp', $user['no_telp']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Alamat</label>
                                        <textarea class="form-control" name="alamat" placeholder="">{{ old('alamat', $user['alamat']) }}</textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Level</label>
                                        <select name="level" class="form-control">
                                            <option value="1" {{ old('level', $user['level']) == "1" ? 'selected' : '' }}>Guru</option>
                                            <option value="2" {{ old('level', $user['level']) == "2" ? 'selected' : '' }}>Admin</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <select name="status" class="form-control">
                                            <option value="1" {{ old('status', $user['status']) == "1" ? 'selected' : '' }}>Aktif</option>
                                            <option value="0" {{ old('status', $user['status']) == "0" ? 'selected' : '' }}>Tidak Aktif</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group text-right">
                                        <input type="submit" value="Simpan" class="btn btn-success">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
              </div>
        </div>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title', 'Users')

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Users</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Data Users</h3>
                            </div>
                            @if(Auth::user()->level == 2)
                            <div class="col text-right">
                                <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">Tambah</a>
                            </div>
                            @endif
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Username</th>
                                    <th>TTL</th>
                                    <th>No. Telp</th>
                                    <th>J. Kel</th>
                                    <th>Level</th>
                                    <th>Status</th>
                                    @if(Auth::user()->level == 2)
                                    <th>Aksi</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($users as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $row->nama }}</td>
                                        <td>{{ $row->email }}</td>
                                        <td>{{ $row->username }}</td>
                                        <td>{{ $row->tempat_lhr . ', ' . $row->tgl_lhr }}</td>
                                        <td>{{ $row->no_telp }}</td>
                                        <td>{{ strtoupper($row->j_kel) }}</td>
                                        <td>{!! $row->getLevel() !!}</td>
                                        <td>{!! $row->getStatus() !!}</td>
                                        @if(Auth::user()->level == 2)
                                        <td>
                                            <form action="{{ route('user.destroy', $row->id) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <a href="{{ route('user.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                                <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                        @endif
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="7">Belum ada data</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection