routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('siswa/login', function(){
    return view('auth/login-siswa');
});
Route::post('siswa/login', 'Auth\LoginSiswaController@login')->name('siswa.login');
Route::post('siswa/logout', 'Auth\LoginSiswaController@logout')->name('siswa.logout');
Route::middleware(['auth:siswa'])->prefix('siswa')->group(function(){
    Route::get('dashboard', 'DashboardController@indexSiswa')->name('siswa.dashboard');
    Route::get('kelas', 'KelasController@index')->name('siswa.kelas.index');
    Route::get('kelas/{id}/siswa', 'KelasController@kelasSiswa')->name('siswa.kelas.detail');
    Route::get('pengumuman', 'PengumumanController@index')->name('siswa.pengumuman');
    Route::get('pengumuman/{id}', 'PengumumanController@show')->name('siswa.pengumuman.show');

    Route::get('materi-tugas', 'MateriTugasController@index')->name('siswa.materi-tugas.index');
    Route::get('materi-tugas/{id}', 'MateriTugasController@show')->name('siswa.materi-tugas.show');
    Route::post('materi-tugas/{id}', 'MateriTugasController@submitJawaban')->name('siswa.jawaban');
});

Route::get('/', function () {
    return view('auth/login-siswa');
});

Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', function(){
        return view('dashboard');
    });
    Route::resource('kelas', 'KelasController');
    Route::resource('siswa', 'SiswaController')->middleware('auth:web');
    Route::resource('user', 'UserController')->middleware('auth:web');
    Route::get('kelas/{id}/siswa', 'KelasController@kelasSiswa')->name('kelas.siswa');
    Route::post('kelas/{id}/siswa', 'KelasController@simpanSiswa')->name('kelas.siswa.store');
    Route::delete('kelas/{id}/siswa', 'KelasController@deleteKelasSiswa')->name('kelas.siswa.destroy');

    Route::resource('pengumuman', 'PengumumanController')->middleware('auth:web');
    Route::resource('materi-tugas', 'MateriTugasController');
});

app/Pengumuman.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pengumuman extends Model
{
    protected $table = 'pengumuman';

    protected $fillable = [
        'nama',
        'tgl',
        'isi',
        'status',
        'user_id',
    ];

    public static function getDefaultValues()
    {
        return [
            'nama' => '',
            'tgl' => date('Y-m-d'),
            'isi' => '',
            'status' => '',
            'user_id' => '',
        ];
    }

    public function getStatus() {
        if ($this->status == "1") {
            return '<span class="badge badge-success">Aktif</span>';
        } else {
            return '<span class="badge badge-warning">Tidak Aktif</span>';
        }
    }
}

app/Http/Controllers/PengumumanController.php
<?php

namespace App\Http\Controllers;

use App\Pengumuman;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PengumumanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::guard('web')->check()){
            $data['pengumuman'] = Pengumuman::orderBy('tgl', 'desc')->get();
        } else {
            $data['pengumuman'] = Pengumuman::where('status', 1)->orderBy('tgl', 'desc')->get();
        }
        return view('pengumuman.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['pengumuman'] = Pengumuman::getDefaultValues();

        return view('pengumuman.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'tgl'=> 'required',
            'isi' => 'required',
            'status' => 'required',
        ]);

        $input = $request->toArray();
        $input['user_id'] = Auth::user()->id;
        Pengumuman::create($input);
        return redirect()->route('pengumuman.index')->with('success', 'Berhasil menambah data pengumuman');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\pengumuman  $pengumuman
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['pengumuman'] = Pengumuman::findOrFail($id);
        return view('pengumuman.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\pengumuman  $pengumuman
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['pengumuman'] = Pengumuman::findOrFail($id);
        return view('pengumuman.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\pengumuman  $pengumuman
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required',
            'tgl'=> 'required',
            'isi' => 'required',
            'status' => 'required',
        ]);
        $input = $request->toArray();
        $input['user_id'] = Auth::user()->id;
        Pengumuman::findOrfail($id)->update($input);
        return redirect()->route('pengumuman.index')->with('success', 'Berhasil mengubah data pengumuman');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\pengumuman  $pengumuman
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Pengumuman::findOrfail($id)->delete();
        return redirect()->route('pengumuman.index')->with('success', 'Berhasil menghapus data pengumuman');
    }
}

resources/views/pengumuman/form.blade.php
@extends('layouts.app')

@section('title', 'Form Pengumuman')

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Pengumuman</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                  <div class="row align-items-center">
                    <div class="col-12">
                      <h3 class="mb-0">Form Pengumuman</h3>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <form action="{{ (!isset($pengumuman['id'])) ? route('pengumuman.store') : route('pengumuman.update', $pengumuman['id']) }}" method="post">
                        @csrf
                        @isset($pengumuman['id'])
                            {{ method_field('PUT')}}
                        @endisset
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Nama Pengumuman</label>
                                        <input type="text" class="form-control" name="nama" placeholder="" value="{{ old('nama', $pengumuman['nama']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Tanggal</label>
                                        <input type="text" class="form-control datepicker" name="tgl" placeholder="" value="{{ old('tgl', $pengumuman['tgl']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Isi</label>
                                        <textarea type="text" class="form-control" name="isi" placeholder="">{{ old('isi', $pengumuman['isi']) }}</textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <select name="status" class="form-control">
                                            <option value="1" {{ old('status', $pengumuman['status']) == "1" ? 'selected' : '' }}>Aktif</option>
                                            <option value="0" {{ old('status', $pengumuman['status']) == "0" ? 'selected' : '' }}>Tidak Aktif</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group text-right">
                                        <input type="submit" value="Simpan" class="btn btn-success">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
              </div>
        </div>
    </div>

@endsection

resources/views/pengumuman/index.blade.php
@extends('layouts.app')

@section('title', 'Pengumuman')

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Pengumuman</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Data Pengumuman</h3>
                            </div>
                            <div class="col text-right">
                                @if(Auth::guard('web')->check())
                                    <a href="{{ route('pengumuman.create') }}" class="btn btn-sm btn-primary">Tambah</a>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Nama pengumuman</th>
                                    <th>Tgl</th>
                                    <th>Status</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($pengumuman as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $row->nama }}</td>
                                        <td>{{ $row->tgl }}</td>
                                        <td>{!! $row->getStatus() !!}</td>
                                        <td>
                                            @if(Auth::guard('web')->check())
                                                <form action="{{ route('pengumuman.destroy', $row->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <a href="{{ route('pengumuman.show', $row->id) }}" class="btn btn-sm btn-info" title="Lihat detail"><i class="fa fa-eye"></i></a>
                                                    <a href="{{ route('pengumuman.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                                    <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                                </form>
                                            @else
                                                <a href="{{ route('siswa.pengumuman.show', $row->id) }}" class="btn btn-sm btn-info" title="Lihat detail"><i class="fa fa-eye"></i></a>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="7">Belum ada data</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/pengumuman/show.blade.php
@extends('layouts.app')

@section('title', 'Detail Pengumuman')

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Detail Pengumuman</h6>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">{{ $pengumuman->nama }}</h3>
                            </div>
                            <div class="col text-right">
                                {!! $pengumuman->getStatus() !!}
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>{{ $pengumuman->tgl }}</p>
                        <pre style="font-family: 'Open Sans'; line-height:1.8em; color:#525f7f;">{{ $pengumuman->isi }}</pre>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection