routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('siswa/login', function(){
    return view('auth/login-siswa');
});
Route::post('siswa/login', 'Auth\LoginSiswaController@login')->name('siswa.login');
Route::post('siswa/logout', 'Auth\LoginSiswaController@logout')->name('siswa.logout');
Route::middleware(['auth:siswa'])->prefix('siswa')->group(function(){
    Route::get('dashboard', 'DashboardController@indexSiswa')->name('siswa.dashboard');
    Route::get('kelas', 'KelasController@index')->name('siswa.kelas.index');
    Route::get('kelas/{id}/siswa', 'KelasController@kelasSiswa')->name('siswa.kelas.detail');
    Route::get('pengumuman', 'PengumumanController@index')->name('siswa.pengumuman');
    Route::get('pengumuman/{id}', 'PengumumanController@show')->name('siswa.pengumuman.show');

    Route::get('materi-tugas', 'MateriTugasController@index')->name('siswa.materi-tugas.index');
    Route::get('materi-tugas/{id}', 'MateriTugasController@show')->name('siswa.materi-tugas.show');
    Route::post('materi-tugas/{id}', 'MateriTugasController@submitJawaban')->name('siswa.jawaban');
});

Route::get('/', function () {
    return view('auth/login-siswa');
});

Auth::routes();

Route::middleware(['auth:web'])->group(function(){
    Route::get('dashboard', function(){
        return view('dashboard');
    });
    Route::resource('kelas', 'KelasController');
    Route::resource('siswa', 'SiswaController')->middleware('auth:web');
    Route::resource('user', 'UserController')->middleware('auth:web');
    Route::get('kelas/{id}/siswa', 'KelasController@kelasSiswa')->name('kelas.siswa');
    Route::post('kelas/{id}/siswa', 'KelasController@simpanSiswa')->name('kelas.siswa.store');
    Route::delete('kelas/{id}/siswa', 'KelasController@deleteKelasSiswa')->name('kelas.siswa.destroy');

    Route::resource('pengumuman', 'PengumumanController')->middleware('auth:web');
    Route::resource('materi-tugas', 'MateriTugasController');
});

app/Kelas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    protected $table = 'kelas';

    protected $fillable = [
        'nama_kelas',
        'tahun_ajar',
        'status',
    ];

    public static function getDefaultValues()
    {
        return [
            'nama_kelas' => '',
            'tahun_ajar' => '',
            'status' => '',
        ];
    }

    public function getStatus() {
        if ($this->status == "1") {
            return '<span class="badge badge-success">Aktif</span>';
        } else {
            return '<span class="badge badge-warning">Tidak Aktif</span>';
        }
    }
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use App\Kelas;
use App\KelasSiswa;
use App\Siswa;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Auth::guard('web')->check()){
            $data['kelas'] = Kelas::orderBy('tahun_ajar', 'desc')->get();
        } else {
            $data['kelas'] = Siswa::find(Auth::user()->id)->getKelasSiswa();
        }
        return view('kelas.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['kelas'] = Kelas::getDefaultValues();

        return view('kelas.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama_kelas' => 'required|unique:kelas,nama_kelas',
            'tahun_ajar'=> 'required',
            'status' => 'required',
        ]);

        Kelas::create($request->toArray());
        return redirect()->route('kelas.index')->with('success', 'Berhasil menambah data kelas');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function show(Kelas $kelas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['kelas'] = Kelas::findOrFail($id);
        return view('kelas.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama_kelas' => 'required',
            'tahun_ajar'=> 'required',
            'status' => 'required',
        ]);

        Kelas::findOrfail($id)->update($request->toArray());
        return redirect()->route('kelas.index')->with('success', 'Berhasil mengubah data kelas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kelas::findOrfail($id)->delete();
        return redirect()->route('kelas.index')->with('success', 'Berhasil menghapus data kelas');
    }

    public function kelasSiswa($id) {
        $data['kelas'] = Kelas::findOrfail($id);
        $data['siswa'] = KelasSiswa::where('kelas_id', $id)->get();
        $data['daftar_siswa'] = Siswa::getAvailableSiswa();
        return view('kelas.siswa', $data);
    }

    public function simpanSiswa(Request $request, $id)
    {
        $request->validate([
            'siswa_id' => 'required'
        ]);

        KelasSiswa::create([
            'kelas_id' => $id,
            'siswa_id' => $request->siswa_id,
            'status' => 1,
        ]);

        return redirect()->back()->with('success', 'Berhasil menambah data siswa ke kelas');

    }

    public function deleteKelasSiswa($id) {
        KelasSiswa::findOrFail($id)->delete();
        return redirect()->back()->with('success', 'Berhasil menghapus siswa dari kelas');
    }
}

resources/views/kelas/form.blade.php
@extends('layouts.app')

@section('title', 'Form Kelas')

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Kelas</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="col-8">
            <div class="card">
                <div class="card-header">
                  <div class="row align-items-center">
                    <div class="col-12">
                      <h3 class="mb-0">Form Kelas</h3>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <form action="{{ (!isset($kelas['id'])) ? route('kelas.store') : route('kelas.update', $kelas['id']) }}" method="post">
                        @csrf
                        @isset($kelas['id'])
                            {{ method_field('PUT')}}
                        @endisset
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Nama Kelas</label>
                                        <input type="text" class="form-control" name="nama_kelas" placeholder="Contoh: 10A, 11B" value="{{ old('nama_kelas', $kelas['nama_kelas']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Tahun Ajar</label>
                                        <input type="text" class="form-control" name="tahun_ajar" placeholder="Contoh: 2020/2021" value="{{ old('tahun_ajar', $kelas['tahun_ajar']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <select name="status" class="form-control">
                                            <option value="1" {{ old('status', $kelas['status']) == "1" ? 'selected' : '' }}>Aktif</option>
                                            <option value="0" {{ old('status', $kelas['status']) == "0" ? 'selected' : '' }}>Tidak Aktif</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group text-right">
                                        <input type="submit" value="Simpan" class="btn btn-success">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
              </div>
        </div>
    </div>

@endsection

resources/views/kelas/index.blade.php
@extends('layouts.app')

@section('title', 'Kelas')

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Kelas</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Data Kelas</h3>
                            </div>
                            <div class="col text-right">
                                @if(Auth::guard('web')->check())
                                    <a href="{{ route('kelas.create') }}" class="btn btn-sm btn-primary">Tambah</a>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Nama Kelas</th>
                                    <th>Tahun Ajar</th>
                                    <th>Status</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($kelas as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $row->nama_kelas }}</td>
                                        <td>{{ $row->tahun_ajar }}</td>
                                        <td>{!! $row->getStatus() !!}</td>
                                        <td>
                                            @if(Auth::guard('web')->check())
                                            <form action="{{ route('kelas.destroy', $row->id) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <a href="{{ route('kelas.siswa', $row->id) }}" class="btn btn-sm btn-info text-white" title="Edit">Siswa</a>
                                                <a href="{{ route('kelas.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                                <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                            </form>
                                            @else
                                                <a href="{{ route('siswa.kelas.detail', $row->id) }}" class="btn btn-sm btn-info text-white" title="Edit">Siswa</a>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="7">Belum ada data</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/kelas/siswa.blade.php
@extends('layouts.app')

@section('title', 'Kelas')

@section('content')
    <div class="header bg-primary pb-5">
      <div class="container-fluid">
        <div class="header-body">
          <div class="row align-items-center py-4">
            <div class="col-lg-6 col-7">
              <h6 class="h2 text-white d-inline-block mb-0">Kelas {{ $kelas->nama_kelas }}</h6>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-8">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Data Siswa Kelas {{ $kelas->nama_kelas }} {{ $kelas->tahun_ajar }}</h3>
                            </div>
                            <div class="col text-right">
                                <!-- Button trigger modal -->
                                @if(Auth::guard('web')->check())
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#formSiswa">
                                    Tambah Siswa
                                </button>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>No Siswa</th>
                                    @if(Auth::guard('web')->check())
                                    <th>Aksi</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($siswa as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $row->siswa->nama }}</td>
                                        <td>{{ $row->siswa->no_siswa }}</td>
                                        @if(Auth::guard('web')->check())
                                        <td>
                                            <form action="{{ route('kelas.siswa.destroy', $row->id) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')">Hapus Dari Kelas</button>
                                            </form>
                                        </td>
                                        @endif
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="7">Belum ada data</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @if(Auth::guard('web')->check())
    <!-- Modal -->
    <div class="modal fade" id="formSiswa" tabindex="-1" role="dialog" aria-labelledby="formSiswaLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="formSiswaLabel">Tambah Siswa</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{{ route('kelas.siswa.store', $kelas->id) }}" method="post">
                    @csrf
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="siswa">Siswa</label>
                            <select class="form-control select2" id="siswa" name="siswa_id">
                                <option>- Pilih Siswa -</option>
                                @foreach($daftar_siswa as $option)
                                    <option value="{{ $option->id }}">{{ $option->nama }} - {{ $option->no_siswa }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    @endif
@endsection